### ISSUE TITLE
serial menu's clear the console

### ISSUE THREAD

**Issue by raboof** [badgeteam/ESP32-platform-firmware#84]
The menu system on the serial is cool, but if you're debugging an app it also thends to clear the screen when you're trying to digest a stack trace :D.

Perhaps we should have an option to enable/disable it?

**Comment by renzenicolai** [comment]
Done

**Comment by raboof** [comment]
It's not quite clear to me what was changed to resolve this issue? I don't see an option to enable/disable it and it still appears to clear the screen.

**Comment by raboof** [comment]
Apparently there is now a 'settings -> homescreen configuration' setting, but that doesn't quite seem to work for me: disabling it indeed gives me a cleaner serial, but also the badge doesn't seem to respond to touch anymore.

**Comment by renzenicolai** [comment]
Bug found, bug fixed in pr https://github.com/badgeteam/ESP32-platform-firmware/pull/93

**Comment by raboof** [comment]
Confirmed fixed
